// <auto-generated />
using System;
using ChemicalSDS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChemicalSDS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521071046_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChemicalSDS.Models.Chemical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcuteHealthEffectsEye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcuteHealthEffectsIngestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcuteHealthEffectsInhalation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcuteHealthEffectsSkin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcuteToxicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcuteToxicityEstimates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AspirationHazard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutoIgnitionTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BioaccumulativePotential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyProtection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoilingPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CASNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carcinogenicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarcinogenicityClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChemicalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChemicalStability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicCarcinogenicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicEffectsGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicHealthEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicMutagenicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicTeratogenicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationJustification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationProcedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionsToAvoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriticalTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfPreviousIssue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfPrinting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecompositionTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevelopmentalEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisposalMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ecotoxicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentalExposureControls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentalHazardsTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentalPrecautionsSpill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaporationRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExposureControls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EyeContactFirstAid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EyeProtection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FertilityEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirefighterProtectiveActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirefighterProtectiveEquipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flammability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlashPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowTimeIso2431")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GasDensity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhsPictogramCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhsPictogramImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HMISRatings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandProtection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlingPrecautions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazardStatements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazardousDecomposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazardousPolymerization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazardsNotOtherwiseClassified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HmisCautionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HmisFlammability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HmisHealth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HmisPhysicalHazards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HygieneMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncompatibleMaterials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngestionFirstAid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InhalationFirstAid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternationalRegulations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrritationCorrosion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<string>("LargeSpillMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastCompletedSection")
                        .HasColumnType("int");

                    b.Property<string>("LongTermDelayedEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongTermImmediateEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LowerExplosiveLimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalAttentionIndication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeltingPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilityInSoil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MolecularWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mutagenicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NFPARatings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NfpaCopyrightNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NfpaFlammability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NfpaHealth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NfpaReactivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NfpaSpecial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesToPhysician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoticeToReader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSHASstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccupationalExposureLimits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccupationalHygiene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Odor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdorThreshold")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherEcologicalEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherMeansOfId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherSkinProtection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackingGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitionCoefficient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Percentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersistenceDegradability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PossibilityOfHazardousReactions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrecautionaryDisposal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrecautionaryGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrecautionaryPrevention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrecautionaryResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrecautionaryStorage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtectionOfFirstAiders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reactivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("References")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegChemWeaponConvention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegCleanAirActClassI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegCleanAirActClassII")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegCleanAirActHaps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegDeaListI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegDeaListII")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryAustralia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryCanada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryChina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryEurope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryJapanEncs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryJapanIshl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryKorea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryMalaysia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryNewZealand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryPhilippines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryTaiwan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryThailand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryTurkey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryUnitedStates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegInventoryVietnam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegMontrealProtocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegRotterdamConvention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegSara302Composition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegSara304RQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegSara311312Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegStateMassachusetts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegStateNewJersey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegStateNewYork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegStatePennsylvania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegStockholmConvention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegTscaCdrExempt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegUneceAarhus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativeDensity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReproductiveToxicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespiratoryProtection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutesOfExposure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SARA302304")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDSNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafeStorageConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sensitization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortTermDelayedEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortTermImmediateEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkinContactFirstAid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmallSpillMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solubility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolubilityInWater")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificHazards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificTreatments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificVolume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpillEmergencyResponders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpillNonEmergencyPersonnel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateRegulations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubstanceMixture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuitableExtinguishingMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synonym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetOrganToxicityRepeated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetOrganToxicitySingle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teratogenicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToxicologicalSymptomsEye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToxicologicalSymptomsIngestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToxicologicalSymptomsInhalation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToxicologicalSymptomsSkin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportBulkMarpol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportDotClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportHazardClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportHazardClassImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportIataClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportRegulations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportSpecialPrecautions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportTdgClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNProperShippingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USFederalRegulations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsuitableExtinguishingMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpperExplosiveLimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaporDensity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaporPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Viscosity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chemicals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviations = "ATE = Acute Toxicity Estimate\nBCF = Bioconcentration Factor\nGHS = Globally Harmonized System of Classification and Labelling of Chemicals\nIATA = International Air Transport Association\nIBC = Intermediate Bulk Container\nIMDG = International Maritime Dangerous Goods\nLogPow = logarithm of the octanol/water partition coefficient\nMARPOL = International Convention for the Prevention of Pollution From Ships, 1973 as modified by the Protocol of 1978. (\"Marpol\" = marine pollution)",
                            AcuteToxicity = "Not available.",
                            AutoIgnitionTemp = "455°C (851°F)",
                            BioaccumulativePotential = "Not available.",
                            BodyProtection = "Personal protective equipment for the body. Anti-static protective clothing.",
                            BoilingPoint = "78.29°C (172.9°F)",
                            CASNumber = "64-17-5",
                            Carcinogenicity = "Not available.",
                            CarcinogenicityClassification = "ethanol|-|1|-",
                            ChemicalName = "ethanol",
                            ChemicalStability = "The product is stable.",
                            Classification = "FLAMMABLE LIQUIDS - Category 2",
                            ClassificationJustification = "Expert judgment",
                            ClassificationProcedure = "FLAMMABLE LIQUIDS - Category 2",
                            Color = "Colorless. Clear.",
                            ConditionsToAvoid = "Avoid all possible sources of ignition (spark or flame). Do not pressurize, cut, weld, braze, solder, drill, grind or expose containers to heat or sources of ignition. Do not allow vapor to accumulate in low or confined areas.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfPreviousIssue = "No previous validation",
                            DateOfPrinting = "4/8/2019",
                            DateOfRevision = "4/8/2019",
                            DisposalMethods = "The generation of waste should be avoided or minimized wherever possible. Dispose of surplus and non-recyclable products via a licensed waste disposal contractor. Empty containers or liners may retain some product residues. Do not cut, weld or grind used containers unless they have been cleaned thoroughly internally.",
                            Ecotoxicity = "Acute EC50 17.921 mg/l Marine water Algae - 96 hours. Acute EC50 2000 µg/l Fresh water Daphnia - 48 hours.",
                            EmergencyPhone = "1-866-734-3438",
                            ExposureControls = "Use only with adequate ventilation. Use explosion-proof ventilation equipment.",
                            EyeContactFirstAid = "Immediately flush eyes with plenty of water, occasionally lifting the upper and lower eyelids. Check for and remove any contact lenses. Continue to rinse for at least 10 minutes. Get medical attention if irritation occurs.",
                            EyeProtection = "Safety eyewear complying with an approved standard should be used. Safety glasses with side shields.",
                            FlashPoint = "Closed cup: 9.7°C (49.5°F)",
                            HMISRatings = "Health: 1, Flammability: 4, Physical hazards: 0",
                            HandProtection = "Chemical-resistant, impervious gloves complying with an approved standard should be worn.",
                            HandlingPrecautions = "Wear protective gloves. Use only with adequate ventilation.",
                            HazardStatements = "May form explosive mixtures with air.\nHighly flammable liquid and vapor.",
                            HazardousDecomposition = "Decomposition products may include the following materials: carbon dioxide, carbon monoxide",
                            HazardousPolymerization = "Under normal conditions of storage and use, hazardous polymerization will not occur.",
                            HazardsNotOtherwiseClassified = "None known.",
                            HmisFlammability = "4",
                            HmisHealth = "1",
                            HmisPhysicalHazards = "0",
                            IncompatibleMaterials = "Reactive or incompatible with the following materials: oxidizing materials",
                            IngestionFirstAid = "Wash out mouth with water. Remove dentures if any. Remove victim to fresh air and keep at rest in a position comfortable for breathing. If material has been swallowed and the exposed person is conscious, give small quantities of water to drink. Stop if the exposed person feels sick as vomiting may be dangerous. Do not induce vomiting unless directed to do so by medical personnel. If vomiting occurs, the head should be kept low so that vomit does not enter the lungs. Get medical attention if adverse health effects persist or are severe. Never give anything by mouth to an unconscious person.",
                            IngredientName = "ethanol",
                            InhalationFirstAid = "Remove victim to fresh air and keep at rest in a position comfortable for breathing. If not breathing, if breathing is irregular or if respiratory arrest occurs, provide artificial respiration or oxygen by trained personnel. It may be dangerous to the person providing aid to give mouth-to-mouth resuscitation. Get medical attention if adverse health effects persist or are severe. If unconscious, place in recovery position and get medical attention immediately.",
                            InventoryList = "Australia: Listed. Canada: Listed. China: Listed. Europe: Listed. Japan: Listed. United States: Listed.",
                            IrritationCorrosion = "ethanol|Eyes - Mild irritant|Rabbit|-|24 hours 500 milligrams|-\nethanol|Eyes - Moderate irritant|Rabbit|-|0.066666667 minutes 100 milligrams|-\nethanol|Eyes - Moderate irritant|Rabbit|-|100 microliters|-\nethanol|Eyes - Severe irritant|Rabbit|-|500 milligrams|-\nethanol|Skin - Mild irritant|Rabbit|-|400 milligrams|-\nethanol|Skin - Moderate irritant|Rabbit|-|24 hours 20 milligrams|-",
                            IsDeleted = false,
                            IsDraft = false,
                            LargeSpillMethods = "Stop leak if without risk. Move containers from spill area. Use spark-proof tools and explosion-proof equipment. Approach release from upwind. Prevent entry into sewers, water courses, basements or confined areas. Contain and collect spillage with non-combustible, absorbent material e.g. sand, earth, vermiculite or diatomaceous earth and place in container for disposal according to local regulations. Dispose of via a licensed waste disposal contractor.",
                            LastCompletedSection = 16,
                            LowerExplosiveLimit = "3.3%",
                            MeltingPoint = "-114°C (-173.2°F)",
                            NFPARatings = "Health: 1, Flammability: 4, Instability/Reactivity: 0",
                            NfpaFlammability = "4",
                            NfpaHealth = "1",
                            NfpaReactivity = "0",
                            NoticeToReader = "To the best of our knowledge, the information contained herein is accurate. However, neither the above-named supplier, nor any of its subsidiaries, assumes any liability whatsoever for the accuracy or completeness of the information contained herein. Final determination of suitability of any material is the sole responsibility of the user. All materials may present unknown hazards and should be used with caution. Although certain hazards are described herein, we cannot guarantee that these are the only hazards that exist.",
                            OSHASstatus = "This material is considered hazardous by the OSHA Hazard Communication Standard (29 CFR 1910.1200).",
                            Odor = "Characteristic.",
                            OtherMeansOfId = "ethyl alcohol; ALCOHOL; Ethyl alcohol (Ethanol); EtOH; Grain alcohol; Cologne spirit; Denatured Alcohol; METHYLCARBINOL",
                            PackingGroup = "II",
                            Percentage = "100",
                            PhysicalState = "Liquid.",
                            PrecautionaryDisposal = "Dispose of contents and container in accordance with all local, regional, national and international regulations.",
                            PrecautionaryGeneral = "Read label before use. Keep out of reach of children. If medical advice is needed, have product container or label at hand.",
                            PrecautionaryPrevention = "Wear protective gloves. Wear eye or face protection. Keep away from heat, sparks, open flames and hot surfaces. - No smoking. Use explosion-proof electrical, ventilating, lighting and all material-handling equipment. Use only non-sparking tools. Take precautionary measures against static discharge. Keep container tightly closed. Use and store only outdoors or in a well ventilated place.",
                            PrecautionaryResponse = "IF ON SKIN (or hair): Take off immediately all contaminated clothing. Rinse skin with water or shower.",
                            PrecautionaryStorage = "Store in a well-ventilated place. Keep cool.",
                            ProductCode = "001114",
                            ProductIdentifier = "Ethanol",
                            ProductType = "Liquid.",
                            ProductUse = "Synthetic/Analytical chemistry.",
                            Quantity = 5.5m,
                            References = "Not available.",
                            RegChemWeaponConvention = "Not listed.",
                            RegCleanAirActClassI = "Not listed",
                            RegCleanAirActClassII = "Not listed",
                            RegCleanAirActHaps = "Not listed",
                            RegDeaListI = "Not listed",
                            RegDeaListII = "Not listed",
                            RegInventoryAustralia = "This material is listed or exempted.",
                            RegInventoryCanada = "This material is listed or exempted.",
                            RegInventoryChina = "This material is listed or exempted.",
                            RegInventoryEurope = "This material is listed or exempted.",
                            RegInventoryJapanEncs = "This material is listed or exempted.",
                            RegInventoryJapanIshl = "This material is listed or exempted.",
                            RegInventoryKorea = "This material is listed or exempted.",
                            RegInventoryMalaysia = "This material is listed or exempted.",
                            RegInventoryNewZealand = "This material is listed or exempted.",
                            RegInventoryPhilippines = "This material is listed or exempted.",
                            RegInventoryTaiwan = "This material is listed or exempted.",
                            RegInventoryThailand = "Not determined",
                            RegInventoryTurkey = "This material is listed or exempted.",
                            RegInventoryUnitedStates = "This material is listed or exempted.",
                            RegInventoryVietnam = "Not determined",
                            RegMontrealProtocol = "Not listed.",
                            RegRotterdamConvention = "Not listed.",
                            RegSara302Composition = "No products were found.",
                            RegSara304RQ = "Not applicable.",
                            RegSara311312Classification = "Refer to Section 2: Hazards Identification of this SDS for classification of substance.",
                            RegStateMassachusetts = "This material is listed.",
                            RegStateNewJersey = "This material is listed.",
                            RegStateNewYork = "This material is not listed.",
                            RegStatePennsylvania = "This material is listed.",
                            RegStockholmConvention = "Not listed.",
                            RegTscaCdrExempt = "Not determined",
                            RegUneceAarhus = "Not listed.",
                            RelativeDensity = "0.8",
                            RespiratoryProtection = "Based on the hazard and potential for exposure, select a respirator that meets the appropriate standard or certification.",
                            SDSNumber = "001114",
                            SafeStorageConditions = "Store in accordance with local regulations. Store in a segregated and approved area. Store in original container protected from direct sunlight in a dry, cool and well-ventilated area, away from incompatible materials and food and drink. Eliminate all ignition sources. Separate from oxidizing materials. Keep container tightly closed and sealed until ready for use.",
                            SignalWord = "Danger",
                            SkinContactFirstAid = "Flush contaminated skin with plenty of water. Remove contaminated clothing and shoes. Get medical attention if symptoms occur. Wash clothing before reuse. Clean shoes thoroughly before reuse.",
                            SmallSpillMethods = "Stop leak if without risk. Move containers from spill area. Use spark-proof tools and explosion-proof equipment. Dilute with water and mop up if water-soluble. Alternatively, or if water-insoluble, absorb with an inert dry material and place in an appropriate waste disposal container. Dispose of via a licensed waste disposal contractor.",
                            Solubility = "1000 g/l",
                            SpecificHazards = "Highly flammable liquid and vapor. Runoff to sewer may create fire or explosion hazard. In a fire or if heated, a pressure increase will occur and the container may burst, with the risk of a subsequent explosion. The vapor/gas is heavier than air and will spread along the ground. Vapors may accumulate in low or confined areas or travel a considerable distance to a source of ignition and flash back.",
                            StateRegulations = "Massachusetts: This material is listed. New Jersey: This material is listed. Pennsylvania: This material is listed.",
                            StorageLocation = "Flammable Cabinet A-12",
                            SubstanceMixture = "Substance",
                            SuitableExtinguishingMedia = "Use dry chemical, CO₂, water spray (fog) or foam.",
                            SupplierDetails = "Airgas USA, LLC and its affiliates\n259 North Radnor-Chester Road\nSuite 100\nRadnor, PA 19087-5283\n1-610-687-5253",
                            Synonym = "ethyl alcohol; ALCOHOL; Ethyl alcohol (Ethanol); EtOH",
                            TransportHazardClass = "3",
                            UNNumber = "UN1170",
                            UNProperShippingName = "ETHANOL OR ETHYL ALCOHOL OR ETHANOL SOLUTIONS",
                            USFederalRegulations = "TSCA 8(a) CDR Exempt/Partial exemption: Not determined. Clean Air Act: Not listed. SARA 302/304: Not listed.",
                            Unit = "Liters",
                            UnsuitableExtinguishingMedia = "Do not use water jet.",
                            UpperExplosiveLimit = "19%",
                            VaporDensity = "1.6 (Air = 1)",
                            VaporPressure = "5.7 kPa (42.95 mm Hg) [room temperature]",
                            Version = "1"
                        });
                });

            modelBuilder.Entity("ChemicalSDS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
